### ISSUE TITLE
Nueva charla para la agenda

### ISSUE THREAD

**Issue by Djkde01** [Backbone-UTP/main-page#17]
Se confirmó una nueva charla, que debe ser añadida en el el JSON `agenda` en `src/assets/content/sfd-features.ts`

```
flag: 'Mariana Cortes Rueda'
time: '03:30 - 04:00'
description: ''10 tips para cambiar tu mundo documentando en Open Source.'
```

**Comment by JGaviria0** [comment]
Hay  una nueva forma de agregar las carlas, se requieren estos campos: 

javascript ```
{
    name: 'Nombre del ponente',
    description: 'Breve descripcion del ponente',
    talk: 'Nombre de la charla',
    time: 'horario en formato HH:MM - HH:MM',
    img: "direccion de la imagen del ponente ( debe estar en /assets/images/speakers/{{nombre del ponente}}.png"
}
```

**Comment by JGaviria0** [comment]
Usar esta rama: 

git fetch origin
git checkout feat/17

**Comment by JGaviria0** [comment]
{
    name: 'Mariana Cortés Rueda',
    description: 'Es comunicadora de profesión y actualmente se dedica a la documentación técnica (tech writer), después de haber estudiado y ejercido como programadora frontend. Ella se ha propuesto ayudar a crear puentes entre desarrolladores o ingenieros, ejecutivos, y usuarios por medio de comunicaciones efectivas.',
    talk: '10 tips para cambiar tu mundo documentando en Open Source',
    time: '03:30 - 04:00',
    img: ""
  },
