### ISSUE TITLE
bug: El temporizador no apunta a la fecha planteada

### ISSUE THREAD

**Issue by Mega-Barto** [Backbone-UTP/main-page#49]
Se supone que el evento inicia a las 8 am del 10 de octubre.
Haciendo cálculos del tiempo ilustrado en la página, apunta al 8 de octubre aproximadamente.

**Comment by Djkde01** [comment]
Cerrando como duplicado, ya que fue reportado en https://github.com/Backbone-UTP/main-page/issues/33
